{
 "title": "Home Staking Dashboard",
 "description": "Dashboard for ethereum home staking with eth-docker",
 "tags": [
  "eth",
  "general"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consensus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eth_con_sync_is_syncing{}" }
   ]
  },
  {
   "title": "Execution",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eth_exe_sync_is_syncing{}" }
   ]
  },
  {
   "title": "ETH",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_currency{pair=\"ethusd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_local_validator_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missed Attestations",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(validator_performance_expected_attestations-validator_performance_included_attestations)",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time()-node_boot_time_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gas Price",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Gwei" } },
   "targets": [
    {
     "expr": "eth_exe_gas_price_gwei{}/1000000000",
     "legendFormat": "Gwei"
    }
   ]
  },
  {
   "title": "Block Import",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "beacon_block_import_delay_latest",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Consensus Peers",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(eth_con_peers{ state=\"connected\"})",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "Execution Peers",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "eth_exe_net_peer_count{}", "legendFormat": "Peers" }
   ]
  },
  { "title": "Machine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes{}", "legendFormat": "Total" },
    {
     "expr": "node_memory_MemAvailable_bytes{}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_filesystem_avail_bytes{})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[$__rate_interval]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "-sum(rate(container_network_receive_bytes_total[$__rate_interval]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(-rate(node_disk_written_bytes_total[$__rate_interval]))",
     "legendFormat": "Written"
    },
    {
     "expr": "sum(rate(node_disk_read_bytes_total[$__rate_interval]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "1m" },
    { "expr": "node_load5", "legendFormat": "5m" },
    { "expr": "node_load15", "legendFormat": "15m" }
   ]
  },
  { "title": "Consensus Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Sync Distance",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "slots" } },
   "targets": [
    { "expr": "eth_con_sync_distance{}", "legendFormat": "Distance" }
   ]
  },
  {
   "title": "Sync Percent",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "eth_con_sync_percentage{}", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Reorgs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum by (instance)(increase(eth_con_beacon_reorg_count{}[5m]))",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "Missed Attestations",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "(validator_performance_expected_attestations-validator_performance_included_attestations)",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Epochs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "targets": [
    {
     "expr": "eth_con_beacon_finality_checkpoint_epochs{ state_id=\"head\", checkpoint!=\"previous_justified\"}",
     "legendFormat": "{{ checkpoint }}"
    }
   ]
  },
  {
   "title": "Proposer Delay",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "eth_con_beacon_proposer_delay_sum{} / eth_con_beacon_proposer_delay_count{}",
     "legendFormat": "Delay"
    }
   ]
  },
  {
   "title": "Counts Per Block",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 18 },
   "targets": [
    {
     "expr": "eth_con_beacon_transactions{ block_id=\"head\"}",
     "legendFormat": "Transactions"
    },
    {
     "expr": "eth_con_beacon_slashings{ block_id=\"head\", type=\"proposer\"}",
     "legendFormat": "Proposer Slashings"
    },
    {
     "expr": "eth_con_beacon_slashings{ block_id=\"head\", type=\"attester\"}",
     "legendFormat": "Attester Slashings"
    },
    {
     "expr": "eth_con_beacon_attestations{block_id=\"head\"}",
     "legendFormat": "Attestations"
    },
    {
     "expr": "eth_con_beacon_deposits{block_id=\"head\"}",
     "legendFormat": "Deposits"
    },
    {
     "expr": "eth_con_beacon_voluntary_exits{block_id=\"head\"}",
     "legendFormat": "Voluntary Exits"
    }
   ]
  },
  {
   "title": "Epoch distances",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Epochs" } },
   "targets": [
    {
     "expr": "sum by (instance)(\n    eth_con_beacon_finality_checkpoint_epochs{ checkpoint=\"justified\", state_id=\"head\"}\n)\n-\nsum by (instance)(\n    eth_con_beacon_finality_checkpoint_epochs{ checkpoint=\"finalized\", state_id=\"head\"}\n)",
     "legendFormat": "Justified -> Finalized"
    },
    {
     "expr": "sum by (instance)(\n    eth_con_beacon_finality_checkpoint_epochs{ checkpoint=\"justified\", state_id=\"head\"}\n)\n-\nsum by (instance)(\n    eth_con_beacon_finality_checkpoint_epochs{ checkpoint=\"previous_justified\", state_id=\"head\"}\n)",
     "legendFormat": "Justified -> Previous Justified"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "\n    eth_con_beacon_slot{ slot!=\"genesis\"}\n",
     "legendFormat": "{{ block_id }}"
    }
   ]
  },
  { "title": "Execution Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Sync Distance",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "targets": [
    {
     "expr": "eth_exe_sync_highest_block{} - eth_exe_sync_current_block{}",
     "legendFormat": "Distance"
    }
   ]
  },
  {
   "title": "Sync Percent",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "eth_exe_sync_percentage{}", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "MemPool TXs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "besu_transaction_pool_transactions",
     "legendFormat": "Pending TXs"
    }
   ]
  },
  {
   "title": "Gas Used ",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance)(\n    eth_exe_block_head_gas_used{}\n)\n/\nsum by (instance)( \n    eth_exe_block_head_gas_limit{} \n)",
     "legendFormat": "Gas Used"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "eth_exe_block_most_recent_number{}",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Block size",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "eth_exe_block_head_block_size_bytes{}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Consensus Spec",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (version)(eth_exe_web3_client_version{})",
       "legendFormat": "{{ version }}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (version)(eth_con_node_version{})",
       "legendFormat": "{{ version }}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "eth_con_fork_current{}", "legendFormat": "{{ fork }}" }
     ]
    },
    {
     "title": "Consensus Spec",
     "type": "table",
     "gridPos": { "h": 25, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum by (spec)(\n    label_replace(\n        {__name__=~\"eth_con_spec.*\", },\n        \"spec\",\n        \"$1\",\n        \"__name__\",\n        \"eth_con_spec_(.*)\"\n    )\n)",
       "legendFormat": "{{ spec }}"
      }
     ]
    }
   ]
  }
 ]
}