volumes:
  database_postgres:
  nginx_log:

networks:
  tools:
   name: tools
   external: true
  

services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    ports:
    - "8070:3000"
    - "8090:9090"
    - "8080:15080"
    - "15000:15000"
    - "15432:15432"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - nginx_log:/var/log/nginx/
    restart: always
    networks:
      - tools