global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'node-exporter'
  static_configs:
  - targets: ['node-exporter:9100']

- job_name: 'cadvisor'
  static_configs:
  - targets: ['cadvisor:8080']

- job_name: 'rabbitmq-server'
  static_configs:
  - targets:
    - 'rabbit-1:15692'
    - 'rabbit-2:15692'
    - 'rabbit-3:15692'

- job_name: postgres-exporter
  static_configs:
  - targets: ["postgres-exporter:9187"]
