networks:
  tools:
   name: tools
   external: true

services:
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer
    hostname: producer
    environment:
      RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
    networks:
      - tools   

  consumer:
    depends_on:
      - producer
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: consumer
    hostname: consumer
    environment:
      RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    networks:
      - tools

  api:
    depends_on:
      - consumer
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    hostname: api
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "8000:8000"
    networks:
      - tools
